In [1]:
import numpy as np

# Laboratorium 1 

Zasada działa neuronu oraz budowa prostej sieci neuronowe

### Zadanie 1

Implementacja funkcji neuron której zadaniem jest obliczenie odpowiedzi pojedynczego neuronu.

Funkcja powinna przyjmować trzy parametry: **input**, **weights**, **bias**

In [35]:
def neuron(input_data=[], weights=[], bias=0):
    return weights.dot(input_data) + bias

input_data = np.array([[0.5], [0.75], [0.1], [0.4], [0.9]])
weights = np.array([0.1, 0.1, -0.3, 0.5, 0.1])

print(f"Input data:\n{input_data}\n")
print(f"Weights:\n{weights}\n")
print(f"Result:\n{neuron(input_data, weights)}")

Input data:
[[0.5 ]
 [0.75]
 [0.1 ]
 [0.4 ]
 [0.9 ]]

Weights:
[ 0.1  0.1 -0.3  0.5  0.1]

Result:
[0.385]


### Zadanie 2

Implementacja prostej sieci neuronowej, która na wejściu otrzyma **wektor wartości wejściowych** oraz **macierz wag**.

Funkcja powinna zwrócić wektor z wartoścami dla poszczególnych neuronów.

In [37]:
class NeuralNetwork():
    def __init__(self, input_data=[], weights=[]):
        self.input_data = input_data
        self.weights = weights
        
    def calcualte_network(self):
        return self.weights.dot(self.input_data)
    
input_data = np.array([[0.5], [0.75], [0.1]])
weights = np.array([[0.1, 0.1, -0.3],[0.1, 0.2, 0.0],[0.0, 0.7, 0.1],[0.2, 0.4, 0.0],[-0.3, 0.5, 0.1]])
network = NeuralNetwork(input_data, weights)

print(f"Input data:\n{input_data}\n")
print(f"Weights:\n{weights}\n")
print(f"Result:\n{network.calcualte_network()}")

Input data:
[[0.5 ]
 [0.75]
 [0.1 ]]

Weights:
[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   0.7  0.1]
 [ 0.2  0.4  0. ]
 [-0.3  0.5  0.1]]

Result:
[[0.095]
 [0.2  ]
 [0.535]
 [0.4  ]
 [0.235]]


### Zadanie 3

Implementacja głębokiej sieci neuronowej, która na wejściu otrzyma **wektor wartości wejściowych** oraz **listę macierzy wag** (wagi dla każdego neuronu w każdej warstwie).

Funkcja powinna zwrócić wektor z wartościami poszczególnych neuronów warstwy wyjściowej.

In [57]:
class DeepNeuralNetwork():
    def __init__(self, input_data=[], weights=[]):
        self.input_data = input_data
        self.weights = weights
        self.layer_idx = 0
        self.num_of_layers = len(self.weights) - 1
        
    def calcualte_deep_network(self):
        def calcualte_layer(input_data, weights):
            self.input_data = weights.dot(self.input_data)
            self.layer_idx += 1
            return self.input_data
        while True:
            if self.layer_idx == self.num_of_layers:
                return calcualte_layer(self.input_data, self.weights[self.layer_idx])
            else:
                calcualte_layer(self.input_data, self.weights[self.layer_idx])
    
input_data = np.array([[0.5], [0.75], [0.1]])
weights_hidden = np.array([[0.1, 0.1, -0.3],[0.1, 0.2, 0.0],[0.0, 0.7, 0.1],[0.2, 0.4, 0.0],[-0.3, 0.5, 0.1]])
weights_output = np.array([[0.7, 0.9, -0.4, 0.8, 0.1],[0.8, 0.5, 0.3, 0.1, 0.0],[-0.3, 0.9, 0.3, 0.1, -0.2]])
deep_network = DeepNeuralNetwork(input_data, [weights_hidden, weights_output])

print(f"Input data:\n{input_data}\n")
print(f"Hidden layer weights:\n{weights_hidden}\n")
print(f"Output layer weights:\n{weights_output}\n")
print(f"Result:\n{deep_network.calcualte_deep_network()}")

Input data:
[[0.5 ]
 [0.75]
 [0.1 ]]

Hidden layer weights:
[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   0.7  0.1]
 [ 0.2  0.4  0. ]
 [-0.3  0.5  0.1]]

Output layer weights:
[[ 0.7  0.9 -0.4  0.8  0.1]
 [ 0.8  0.5  0.3  0.1  0. ]
 [-0.3  0.9  0.3  0.1 -0.2]]

Result:
[[0.376 ]
 [0.3765]
 [0.305 ]]


### Zadanie 4

Stworzenie API pozwalającego na budowanie sieci składająćej się z warstw w pełni połączonych. Zaimplementowane rozwiązanie ma umożliwić budowanie sieci o dowolnej liczbie neuronów wejściowych oraz wyjściowych, dowolnej liczbie warstw ukrytych z dowolną liczbą neuronów. W początkwoej fazie działania programu pwoinno nastąpić henerowanie losowych wartości wag dla każdej warstwy zbudowanej sieci. 

Wymagane funkcje:

* **add layer(n, [weight min value, weight max value])**

* **predict(input)**

* **load weights(file name)**

In [ ]:
class DeepNeuralNetwork():
    def __init__(self):
        pass
    
    def add_layer(self, num_of_neurons, weights_range=None):
        pass
    
    def predict(self, input_data=[]):
        pass
    
    def load_weights(self, num_of_neurons, weights_range):
        pass