In [1]:
import numpy as np
from typing import List
from pprint import pprint as pp

# Laboratorium 1 

Zasada działania neuronu oraz budowa prostej sieci neuronowej

## Zadanie 1

Implementacja funkcji neuron której zadaniem jest obliczenie odpowiedzi pojedynczego neuronu.

Funkcja powinna przyjmować trzy parametry: **input**, **weights**, **bias**

In [2]:
def neuron(input_data=[], weights=[], bias=0):
    return weights.dot(input_data) + bias

input_data = np.array([[0.5], [0.75], [0.1], [0.4], [0.9]])
weights = np.array([0.1, 0.1, -0.3, 0.5, 0.1])

print(f"Input data:\n{input_data}\n")
print(f"Weights:\n{weights}\n")
print(f"Result:\n{neuron(input_data, weights)}")

Input data:
[[0.5 ]
 [0.75]
 [0.1 ]
 [0.4 ]
 [0.9 ]]

Weights:
[ 0.1  0.1 -0.3  0.5  0.1]

Result:
[0.385]


## Zadanie 2

Implementacja prostej sieci neuronowej, która na wejściu otrzyma **wektor wartości wejściowych** oraz **macierz wag**.

Funkcja powinna zwrócić wektor z wartoścami dla poszczególnych neuronów.

In [3]:
class NeuralNetwork():
    def __init__(self, input_data=[], weights=[]):
        self.input_data = input_data
        self.weights = weights
        
    def calcualte_network(self):
        return self.weights.dot(self.input_data)
    
input_data = np.array([[0.5], [0.75], [0.1]])
weights = np.array([[0.1, 0.1, -0.3],[0.1, 0.2, 0.0],[0.0, 0.7, 0.1],[0.2, 0.4, 0.0],[-0.3, 0.5, 0.1]])
network = NeuralNetwork(input_data, weights)

print(f"Input data:\n{input_data}\n")
print(f"Weights:\n{weights}\n")
print(f"Result:\n{network.calcualte_network()}")

Input data:
[[0.5 ]
 [0.75]
 [0.1 ]]

Weights:
[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   0.7  0.1]
 [ 0.2  0.4  0. ]
 [-0.3  0.5  0.1]]

Result:
[[0.095]
 [0.2  ]
 [0.535]
 [0.4  ]
 [0.235]]


## Zadanie 3

Implementacja głębokiej sieci neuronowej, która na wejściu otrzyma **wektor wartości wejściowych** oraz **listę macierzy wag** (wagi dla każdego neuronu w każdej warstwie).

Funkcja powinna zwrócić wektor z wartościami poszczególnych neuronów warstwy wyjściowej.

In [4]:
class DeepNeuralNetwork():
    def __init__(self, input_data=[], weights=[]):
        self.input_data = input_data
        self.weights = weights
        self.layer_idx = 0
        self.num_of_layers = len(self.weights) - 1
        
    def calcualte_deep_network(self):
        def calcualte_layer(input_data, weights):
            self.input_data = weights.dot(self.input_data)
            self.layer_idx += 1
            return self.input_data
        while True:
            if self.layer_idx == self.num_of_layers:
                return calcualte_layer(self.input_data, self.weights[self.layer_idx])
            else:
                calcualte_layer(self.input_data, self.weights[self.layer_idx])
    
input_data = np.array([[0.5], [0.75], [0.1]])
weights_hidden = np.array([[0.1, 0.1, -0.3],[0.1, 0.2, 0.0],[0.0, 0.7, 0.1],[0.2, 0.4, 0.0],[-0.3, 0.5, 0.1]])
weights_output = np.array([[0.7, 0.9, -0.4, 0.8, 0.1],[0.8, 0.5, 0.3, 0.1, 0.0],[-0.3, 0.9, 0.3, 0.1, -0.2]])
deep_network = DeepNeuralNetwork(input_data, [weights_hidden, weights_output])

print(f"Input data:\n{input_data}\n")
print(f"Hidden layer weights:\n{weights_hidden}\n")
print(f"Output layer weights:\n{weights_output}\n")
print(f"Result:\n{deep_network.calcualte_deep_network()}")

Input data:
[[0.5 ]
 [0.75]
 [0.1 ]]

Hidden layer weights:
[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   0.7  0.1]
 [ 0.2  0.4  0. ]
 [-0.3  0.5  0.1]]

Output layer weights:
[[ 0.7  0.9 -0.4  0.8  0.1]
 [ 0.8  0.5  0.3  0.1  0. ]
 [-0.3  0.9  0.3  0.1 -0.2]]

Result:
[[0.376 ]
 [0.3765]
 [0.305 ]]


## Zadanie 4

Stworzenie API pozwalającego na budowanie sieci składająćej się z warstw w pełni połączonych. Zaimplementowane rozwiązanie ma umożliwić budowanie sieci o dowolnej liczbie neuronów wejściowych oraz wyjściowych, dowolnej liczbie warstw ukrytych z dowolną liczbą neuronów. W początkwoej fazie działania programu poinno nastąpić generowanie losowych wartości wag dla każdej warstwy zbudowanej sieci. 

Wymagane funkcje:

* **add layer(n, [weight min value, weight max value])**

* **predict(input)**

In [5]:
class Layer():
    def __init__(self, num_of_neurons, input_dim, weights, weights_range):
        self.num_of_neurons = num_of_neurons
        self.input_dim = input_dim
        self.weights = weights if isinstance(weights, np.ndarray) else self.generate_weights(weights_range)
        self.layer_output = None

    def generate_weights(self, weights_range):
        if weights_range:
            return np.random.uniform(low=0.5, high=13.3, size=(self.num_of_neurons,self.input_dim))
        else:
            return np.random.uniform(size=(self.num_of_neurons,self.input_dim))
        
    def calculate_output(self, input_data):
        self.input_data = input_data
        self.layer_output = self.weights.dot(self.input_data)
        return self.layer_output


class LayerIterator():
    def __init__(self, layers: List[Layer]):
        self.__layers_iterator = iter(layers)
        self.__position = 0 
        self.__num_of_layers = len(layers)
        
    def __next__(self):
        while True:
            if self.__position < self.__num_of_layers:
                self.__position += 1
                return next(self.__layers_iterator)
            raise StopIteration()
    
    
class DeepNeuralNetwork():
    def __init__(self, input_len):
        self._layers = []
        self.last_layer_neurons = input_len
    
    def add_layer(self, num_of_neurons, weights=None, weights_range=None):
        self._layers.append(Layer(num_of_neurons, self.last_layer_neurons, weights, weights_range))
        self.last_layer_neurons = num_of_neurons
    
    def predict(self, input_data=[]):
        for layer in self._layers:
            input_data = layer.calculate_output(input_data)

    def __iter__(self):
        return LayerIterator(self._layers)

input_data = np.array([[0.5], [0.75], [0.1]])

deep_neural_network = DeepNeuralNetwork(len(input_data))
deep_neural_network.add_layer(5)
deep_neural_network.add_layer(3)
deep_neural_network.predict(input_data)

for layer_index, layer in enumerate(deep_neural_network):
    print(f"\nLayer number {layer_index}")
    pp(layer.__dict__)



Layer number 0
{'input_data': array([[0.5 ],
       [0.75],
       [0.1 ]]),
 'input_dim': 3,
 'layer_output': array([[0.79721162],
       [0.65167729],
       [0.94828858],
       [0.46512919],
       [0.52547069]]),
 'num_of_neurons': 5,
 'weights': array([[0.84273562, 0.434969  , 0.49617062],
       [0.80888258, 0.28273285, 0.35186366],
       [0.53893697, 0.8251621 , 0.59948522],
       [0.38683823, 0.29094734, 0.53499568],
       [0.79396906, 0.08937986, 0.61451263]])}

Layer number 1
{'input_data': array([[0.79721162],
       [0.65167729],
       [0.94828858],
       [0.46512919],
       [0.52547069]]),
 'input_dim': 5,
 'layer_output': array([[1.27789756],
       [0.82301896],
       [2.29955646]]),
 'num_of_neurons': 3,
 'weights': array([[0.14079751, 0.24181361, 0.18711231, 0.78904704, 0.88229932],
       [0.00930031, 0.03207201, 0.25760245, 0.49889897, 0.60587605],
       [0.32720886, 0.66616784, 0.84860311, 0.66474514, 0.93375769]])}
